import type {
  AuthorisedStatus,
  BankOnSite,
  BuyerMix,
  Dealership,
  InventoryCountBasis,
  MonthlyFinancedBand,
  MonthlySoldBand,
  SizeBasis,
  VehicleType,
  VisitStatus,
  VolumeFiguresBasis,
} from './types';

interface SeedRow {
  nameEn: string;
  nameAr: string;
  lat: number;
  lng: number;
  phone: string;
  note?: string;
}

// Starting roster for the Al Qadisiyah market, East Riyadh.
// Sourced from mapping data — treat as a list to verify, not a census.
const SEED_ROWS: SeedRow[] = [
  { nameEn: 'AL HALL AL SARI FOR CARS', nameAr: '', lat: 24.8259915, lng: 46.8226078, phone: '+966533093339' },
  { nameEn: 'Automax', nameAr: '', lat: 24.8301255, lng: 46.8364122, phone: '+966533077000' },
  { nameEn: 'AlWadi Car', nameAr: 'معرض مركبة الوادي للسيارات فرع القادسيه', lat: 24.824768, lng: 46.8174393, phone: '+966580646002' },
  { nameEn: 'Carly', nameAr: 'كارلي', lat: 24.8291207, lng: 46.8248513, phone: '+966920016302', note: 'COMPETITOR — embedded finance' },
  { nameEn: 'Sayaratk Cars Co.', nameAr: 'شركة سيارتك للسيارات', lat: 24.8312385, lng: 46.8281159, phone: '+966595066097' },
  { nameEn: 'Exit 8 Car Dealer', nameAr: '', lat: 24.8224692, lng: 46.8254390, phone: '+966557974899' },
  { nameEn: 'Alhamidi Cars Company', nameAr: '', lat: 24.8244831, lng: 46.8224061, phone: '+966503543287' },
  { nameEn: 'Saeed Salem Al Shahrani Cars', nameAr: 'شركة سعيد سالم الشهراني للسيارات', lat: 24.8199375, lng: 46.8251396, phone: '+966556570540' },
  { nameEn: 'Idris Car', nameAr: 'ادريس كار', lat: 24.8252064, lng: 46.8259055, phone: '+966920015755' },
  { nameEn: 'Saleh Group for Cars', nameAr: 'مجموعة صالح للسيارات', lat: 24.8262119, lng: 46.8219016, phone: '+966920022122' },
  { nameEn: 'Soum Cars', nameAr: 'معرض سوم للسيارات', lat: 24.8187947, lng: 46.8243740, phone: '+966540031703', note: 'COMPETITOR — online platform' },
  { nameEn: 'Hala Car Company', nameAr: 'شركة هلا كار للسيارات', lat: 24.8202447, lng: 46.8236137, phone: '+966920013471', note: 'Listed as finance business' },
  { nameEn: 'Sanam United Cars', nameAr: 'معرض سنام المتحدة للسيارات', lat: 24.8305529, lng: 46.8287964, phone: '+966550395924' },
  { nameEn: 'Anwar Al Qadisiyah', nameAr: 'معرض أنوار القادسية', lat: 24.8252899, lng: 46.8290274, phone: '+966555381166' },
  { nameEn: 'Shallal Najd Cars', nameAr: 'معرض شلال نجد للسيارات', lat: 24.8288408, lng: 46.8226635, phone: '+966920002911' },
  { nameEn: 'Imad Eddin Gallery', nameAr: '', lat: 24.8205575, lng: 46.8257539, phone: '+966504448216', note: 'Recently relocated — verify' },
  { nameEn: 'Al Kaif Cars Company', nameAr: 'شركة معرض الكيف للسيارات', lat: 24.8253412, lng: 46.8231903, phone: '+966506113280' },
  { nameEn: 'Ostora Al Qadisiyah Cars', nameAr: 'معرض اسطورة القادسية للسيارات', lat: 24.8246275, lng: 46.8269025, phone: '+966543169787' },
  { nameEn: 'Ramz Al Emarat Cars', nameAr: 'شركة رمز الإمارات للسيارات', lat: 24.8287041, lng: 46.8206782, phone: '+966920015990' },
  { nameEn: 'Al Saber Al Qadisiyah', nameAr: 'معرض السبر القادسية', lat: 24.8277657, lng: 46.8152084, phone: '+966548400654' },
  { nameEn: 'Al Qadisiyah Showrooms', nameAr: 'معارض القادسيه', lat: 24.8312124, lng: 46.8182889, phone: '+966503132638', note: 'COMPLEX — multiple units, split into separate records' },
  { nameEn: 'Abraj Al Qadisiyah Cars', nameAr: 'معرض أبراج القادسية للسيارات', lat: 24.8294822, lng: 46.8240594, phone: '+966507776198' },
  { nameEn: 'Khalaf Cars', nameAr: 'معرض خلف للسيارات', lat: 24.8296347, lng: 46.8185873, phone: '+966534446080' },
  { nameEn: 'Al Buraimi Cars Company', nameAr: 'شركة البريمي للسيارات', lat: 24.8300263, lng: 46.8199979, phone: '+966920033340', note: 'Luxury segment' },
  { nameEn: 'Shaya Cars', nameAr: 'معرض شايع للسيارات', lat: 24.8218341, lng: 46.8266487, phone: '+966557304655' },
  { nameEn: 'Nujoom Al Riyadh Cars', nameAr: 'شركة نجوم الرياض للسيارات', lat: 24.8268807, lng: 46.8139415, phone: '+966920002561' },
  { nameEn: 'Sada Alriyadh Showroom', nameAr: '', lat: 24.8287026, lng: 46.8154649, phone: '+966565653581' },
  { nameEn: 'JMC Aljabr Showroom', nameAr: 'معرض جيه ام سي الجبر', lat: 24.8267100, lng: 46.8053910, phone: '+9668001257777', note: 'AUTHORISED — JMC, contrast case' },
  { nameEn: 'New Car', nameAr: '', lat: 24.8212117, lng: 46.8314468, phone: '+966591233383' },
  { nameEn: 'Al Rumaih Cars', nameAr: 'معرض الرميح للسيارات', lat: 24.8279740, lng: 46.8198680, phone: '+966920031202' },
  { nameEn: 'Al Jood Cars', nameAr: 'معرض الجود للسيارات', lat: 24.8195645, lng: 46.8254648, phone: '+966552379999' },
  { nameEn: 'Al Fakhama Cars', nameAr: 'معرض الفخامه للسيارات', lat: 24.8246293, lng: 46.8234441, phone: '+966534989883' },
  { nameEn: 'Awla Al Markabat Cars', nameAr: 'معرض اولى المركبات للسيارات', lat: 24.8282222, lng: 46.8180986, phone: '+966530014387' },
  { nameEn: 'Bahjat Aseer Cars', nameAr: 'معرض بهجة عسير للسيارات', lat: 24.8304864, lng: 46.8285866, phone: '+966542652233', note: 'Hyundai, Haval, MG' },
  { nameEn: 'Ahdath Cars Ltd', nameAr: 'شركة احدث السيارات المحدودة', lat: 24.8234916, lng: 46.8221556, phone: '+966540998075' },
  { nameEn: 'AZURE Cars', nameAr: '', lat: 24.8283097, lng: 46.8167385, phone: '+966502667999' },
  { nameEn: 'Raed Exhibition of Excellence Cars', nameAr: '', lat: 24.8245769, lng: 46.8245830, phone: '+966535333766' },
  { nameEn: 'Changan Riyadh Al Humaidi', nameAr: '', lat: 24.8370625, lng: 46.8225625, phone: '', note: 'AUTHORISED — Changan, contrast case' },
];

function initialStatus(note?: string): VisitStatus {
  if (note?.toUpperCase().includes('COMPETITOR')) return 'competitor';
  return 'not_visited';
}

function buildMappingSeedDealerships(): Dealership[] {
  const now = new Date().toISOString();
  return SEED_ROWS.map((row, i) => {
    const id = `seed-${String(i + 1).padStart(3, '0')}`;
    const d: Dealership = {
      id,
      createdAt: now,
      updatedAt: now,
      nameEn: row.nameEn,
      nameAr: row.nameAr,
      lat: row.lat,
      lng: row.lng,
      listedPhone: row.phone,
      note: row.note ?? '',
      isSeed: true,

      visitStatus: initialStatus(row.note),
      visitDate: null,
      surveyor: null,

      crNumber: '',
      showroomSizeSqm: null,
      sizeBasis: null,
      vehicleType: null,
      inventoryAgeMix: null,

      pocName: '',
      pocRole: '',
      pocMobile: '',
      decisionMaker: '',
      numSalesmen: null,

      mainBrands: [],
      authorised: null,
      authorisedBrand: '',
      inventorySellableUnits: { value: null, basis: null },
      inventoryCountBasis: null,
      avgSellingPriceSar: { value: null, basis: null },
      avgMonthlySold: { value: null, basis: null },
      avgMonthlyFinanced: { value: null, basis: null },

      financingLostPerMonth: { value: null, basis: null },
      mainFailReason: '',
      financingWorkaround: '',
      banksPartnered: [],
      bankOnSite: null,

      buyerMix: null,
      leadMixOnlinePct: null,

      volumeFiguresBasis: null,
      openToPilot: null,
      notes: '',

      photoIds: [],
      dirty: false,
    };
    return { ...d, ...(MASTER_ENRICHMENT[row.nameEn] ?? {}) };
  });
}

function buildMasterSurveyDealerships(): Dealership[] {
  const now = new Date().toISOString();
  return MASTER_SURVEY_ROWS.map((row, i) => {
    const d: Dealership = {
      id: `master-${String(i + 1).padStart(3, '0')}`,
      createdAt: now,
      updatedAt: now,
      nameEn: row.nameEn,
      nameAr: row.nameAr,
      lat: row.lat,
      lng: row.lng,
      listedPhone: row.pocMobile,
      note: '',
      isSeed: true,

      visitStatus: row.visitStatus,
      visitDate: null,
      surveyor: null,

      crNumber: '',
      showroomSizeSqm: row.showroomSizeSqm,
      sizeBasis: row.sizeBasis,
      vehicleType: row.vehicleType,
      inventoryAgeMix: null,

      pocName: row.pocName,
      pocRole: row.pocRole,
      pocMobile: row.pocMobile,
      decisionMaker: '',
      numSalesmen: row.numSalesmen,

      mainBrands: row.mainBrands,
      authorised: row.authorised,
      authorisedBrand: row.authorisedBrand,
      inventorySellableUnits: {
        value: row.inventorySellableUnits,
        basis: row.inventorySellableUnits !== null ? 'observed' : null,
      },
      inventoryCountBasis: row.inventoryCountBasis,
      avgSellingPriceSar: {
        value: row.avgSellingPriceSar,
        basis: row.avgSellingPriceSar !== null ? 'self_reported' : null,
      },
      avgMonthlySold: {
        value: row.avgMonthlySold,
        basis: row.avgMonthlySold !== null ? 'self_reported' : null,
      },
      avgMonthlyFinanced: {
        value: row.avgMonthlyFinanced,
        basis: row.avgMonthlyFinanced !== null ? 'self_reported' : null,
      },

      financingLostPerMonth: { value: null, basis: null },
      mainFailReason: '',
      financingWorkaround: row.financingWorkaround,
      banksPartnered: row.banksPartnered,
      bankOnSite: row.bankOnSite,

      buyerMix: row.buyerMix,
      leadMixOnlinePct: row.leadMixOnlinePct,

      volumeFiguresBasis: row.volumeFiguresBasis,
      openToPilot: null,
      notes: row.notes,

      photoIds: [],
      dirty: false,
    };
    return d;
  });
}
// Enrichment for seed rows that are the same physical dealership as a master-table
// field-survey record (matched by name + <20m GPS proximity) — merged, not duplicated.
const MASTER_ENRICHMENT: Record<string, Partial<Dealership>> = {
  'Al Saber Al Qadisiyah': {
    showroomSizeSqm: 2480, sizeBasis: "measured",
    vehicleType: "mix", authorised: "no", authorisedBrand: "",
    buyerMix: "mostly_saudi", mainBrands: ["KIA", "Peugeot", "Nissan New &Benz", "Range Rover Used"],
    pocName: "Ahmed", pocRole: "Sales Manager", pocMobile: "0556188272",
    numSalesmen: 4,
    inventorySellableUnits: { value: 67, basis: 'observed' },
    inventoryCountBasis: "counted",
    avgSellingPriceSar: { value: 200000, basis: 'self_reported' },
    avgMonthlySold: { value: "21_50", basis: 'self_reported' },
    avgMonthlyFinanced: { value: "6_15", basis: 'self_reported' },
    banksPartnered: ["Riyadh", "Rajhi"], bankOnSite: null,
    financingWorkaround: "", leadMixOnlinePct: 70,
    volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~25%",
  },
  'Al Buraimi Cars Company': {
    showroomSizeSqm: 1500, sizeBasis: "estimated",
    vehicleType: "new_only", authorised: "no", authorisedBrand: "",
    buyerMix: null, mainBrands: ["Land Rover", "BMW", "Mercedes-Benz"],
    pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 10,
    inventorySellableUnits: { value: 70, basis: 'observed' },
    inventoryCountBasis: "estimated",
    avgSellingPriceSar: { value: 345000, basis: 'self_reported' },
    avgMonthlySold: { value: null, basis: null },
    avgMonthlyFinanced: { value: null, basis: null },
    banksPartnered: [], bankOnSite: null,
    financingWorkaround: "", leadMixOnlinePct: null,
    volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  'Al Rumaih Cars': {
    showroomSizeSqm: 2400, sizeBasis: "estimated",
    vehicleType: "new_only", authorised: "no", authorisedBrand: "",
    buyerMix: null, mainBrands: ["Jetour", "Haval", "Suzuki"],
    pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3,
    inventorySellableUnits: { value: 90, basis: 'observed' },
    inventoryCountBasis: "estimated",
    avgSellingPriceSar: { value: 75000, basis: 'self_reported' },
    avgMonthlySold: { value: null, basis: null },
    avgMonthlyFinanced: { value: null, basis: null },
    banksPartnered: [], bankOnSite: null,
    financingWorkaround: "", leadMixOnlinePct: null,
    volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  'Al Kaif Cars Company': {
    showroomSizeSqm: 2000, sizeBasis: "estimated",
    vehicleType: "new_only", authorised: "no", authorisedBrand: "",
    buyerMix: null, mainBrands: ["Toyota", "Nissan", "Kia"],
    pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 5,
    inventorySellableUnits: { value: 80, basis: 'observed' },
    inventoryCountBasis: "estimated",
    avgSellingPriceSar: { value: 120000, basis: 'self_reported' },
    avgMonthlySold: { value: null, basis: null },
    avgMonthlyFinanced: { value: null, basis: null },
    banksPartnered: [], bankOnSite: null,
    financingWorkaround: "", leadMixOnlinePct: null,
    volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
};

// Additional dealerships from the field-survey master table — distinct businesses
// from the mapping-data roster above (this market has many showrooms per block).
interface MasterSurveyRow {
  nameEn: string; nameAr: string; lat: number; lng: number;
  showroomSizeSqm: number | null; sizeBasis: SizeBasis; vehicleType: VehicleType | null;
  authorised: AuthorisedStatus; authorisedBrand: string; buyerMix: BuyerMix | null;
  mainBrands: string[]; pocName: string; pocRole: string; pocMobile: string;
  numSalesmen: number | null; inventorySellableUnits: number | null; inventoryCountBasis: InventoryCountBasis;
  avgSellingPriceSar: number | null; avgMonthlySold: MonthlySoldBand | null; avgMonthlyFinanced: MonthlyFinancedBand | null;
  banksPartnered: string[]; bankOnSite: BankOnSite | null; financingWorkaround: string;
  leadMixOnlinePct: number | null; volumeFiguresBasis: VolumeFiguresBasis | null; visitStatus: VisitStatus;
  notes: string;
}

const MASTER_SURVEY_ROWS: MasterSurveyRow[] = [
  {
nameEn: "Abdulsalam Cars Company", nameAr: "شركة عبدالسلام للسيارات", lat: 24.82516, lng: 46.818571,
    showroomSizeSqm: 2250, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: ["Hyundai", "Toyota", "MG"], pocName: "Abdulsalam", pocRole: "Owner", pocMobile: "+966 56 323 4444",
    numSalesmen: 15, inventorySellableUnits: 150, inventoryCountBasis: "counted",
    avgSellingPriceSar: 90000, avgMonthlySold: "100_plus", avgMonthlyFinanced: "40_plus",
    banksPartnered: ["Sanabul", "Raya", "Rajhi", "Alinma"], bankOnSite: "yes_weekly", financingWorkaround: "Raya on-site – 5 days per week",
    leadMixOnlinePct: 80, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~86%",
  },
  {
nameEn: "Salem Car Showroom", nameAr: "معرض سالم للسيارات", lat: 24.824868, lng: 46.817861,
    showroomSizeSqm: 1000, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: ["Toyota", "Lexis", "Minibus"], pocName: "Salem Abu Hamad", pocRole: "Owner", pocMobile: "0555658084",
    numSalesmen: 4, inventorySellableUnits: 70, inventoryCountBasis: "counted",
    avgSellingPriceSar: 150000, avgMonthlySold: "21_50", avgMonthlyFinanced: "16_40",
    banksPartnered: ["Riyadh", "anb"], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: 70, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~60%",
  },
  {
nameEn: "Auto Speed Cars", nameAr: "شركة اوتو سبيد للسيارات", lat: 24.819859, lng: 46.824065,
    showroomSizeSqm: 2470, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: ["Ford", "Nissan"], pocName: "Ahmed", pocRole: "Sales Manager", pocMobile: "0554306909",
    numSalesmen: 2, inventorySellableUnits: 95, inventoryCountBasis: "counted",
    avgSellingPriceSar: 160000, avgMonthlySold: "51_100", avgMonthlyFinanced: "16_40",
    banksPartnered: ["Alinma", "ALJ"], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: 70, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~29%",
  },
  {
nameEn: "NOKHBATY CARS", nameAr: "شركة نخبتي للسيارات", lat: 24.825746, lng: 46.819267,
    showroomSizeSqm: 1000, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: ["Haval", "MG", "Nissan"], pocName: "Abu Hana", pocRole: "Owner", pocMobile: "0550000283",
    numSalesmen: 5, inventorySellableUnits: 60, inventoryCountBasis: "counted",
    avgSellingPriceSar: 100000, avgMonthlySold: "21_50", avgMonthlyFinanced: "16_40",
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: 70, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): Medium · Financing penetration ~63%",
  },
  {
nameEn: "Your Best Car Showroom", nameAr: "معرض سيارتك الأفضل للسيارات", lat: 24.819158, lng: 46.8244,
    showroomSizeSqm: 1200, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "roughly_even",
    mainBrands: ["Ford", "KIA", "MG"], pocName: "Ayman", pocRole: "Sales Manager", pocMobile: "0567251747",
    numSalesmen: 5, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 120000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: ["Rajhi"], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: 80, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "Data credibility (field survey): Low",
  },
  {
nameEn: "Naseem Al-Buraimi Sports Car Showroom", nameAr: "معرض نسيم البريمي للسيارات الرياض", lat: 24.828574, lng: 46.814889,
    showroomSizeSqm: 2900, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: ["Lexis", "Toyota", "Range Rover", "Dongfeng"], pocName: "Salah", pocRole: "Sales", pocMobile: "0509141265",
    numSalesmen: 5, inventorySellableUnits: 82, inventoryCountBasis: "counted",
    avgSellingPriceSar: 300000, avgMonthlySold: "21_50", avgMonthlyFinanced: "6_15",
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~16%",
  },
  {
nameEn: "Adwaa Tuwaiq Automotive Company", nameAr: "شركة أضواء طويق للسيارت", lat: 24.825416, lng: 46.815965,
    showroomSizeSqm: 1200, sizeBasis: "measured", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: "mostly_saudi",
    mainBrands: [], pocName: "Esam", pocRole: "Owner", pocMobile: "050 987 3705",
    numSalesmen: 2, inventorySellableUnits: 30, inventoryCountBasis: "counted",
    avgSellingPriceSar: 300000, avgMonthlySold: "0_20", avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: 70, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "New opened showroom since May · Data credibility (field survey): Medium",
  },
  {
nameEn: "The Falcon Auto Company", nameAr: "شركة الصقر للسيارات", lat: 24.82353, lng: 46.817497,
    showroomSizeSqm: 2000, sizeBasis: "measured", vehicleType: "mix",
    authorised: "no", authorisedBrand: "", buyerMix: "roughly_even",
    mainBrands: ["Hyundai", "Toyota New&Benz", "Cadillac Used"], pocName: "Naser", pocRole: "Sales Manager", pocMobile: "053 996 5652",
    numSalesmen: 4, inventorySellableUnits: 80, inventoryCountBasis: "counted",
    avgSellingPriceSar: 120000, avgMonthlySold: "51_100", avgMonthlyFinanced: "16_40",
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: "self_reported", visitStatus: "completed",
    notes: "Data credibility (field survey): High · Financing penetration ~50%",
  },
  {
nameEn: "Qitaf Cars", nameAr: "شركة قطاف للسيارات", lat: 24.821873, lng: 46.816759,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Geely", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 4, inventorySellableUnits: 95, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 80000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Abraj Al Qimmah Cars", nameAr: "معرض أبراج القمة للسيارات", lat: 24.821998, lng: 46.817028,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Lexus"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 5, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 160000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Tamween Al Hadith", nameAr: "شركة تموين الحديث", lat: 24.822175, lng: 46.817076,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Kia", "Jetour", "Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 4, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 90000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Sevenz Commercial Cars", nameAr: "شركة سفنز التجارية للسيارات", lat: 24.822181, lng: 46.817298,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Jetour", "Haval", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 100000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Ibn Fneis Cars", nameAr: "شركة ابن فنيس للسيارات", lat: 24.822423, lng: 46.817739,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota Land Cruiser", "Ford", "Haval"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 50, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 250000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Masarat Al Raqiyah Trading", nameAr: "شركة المسارات الراقية التجارية", lat: 24.822342, lng: 46.817856,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Lexus", "Toyota", "Jetour"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Ikhtiyar", nameAr: "الاختيار", lat: 24.823137, lng: 46.819492,
    showroomSizeSqm: 2000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Geely"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 8, inventorySellableUnits: 90, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Wilayah Cars", nameAr: "ولاية للسيارات", lat: 24.823211, lng: 46.81979,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Jetour"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Sagheer Cars", nameAr: "شركة معرض الصغير للسيارات", lat: 24.823326, lng: 46.819871,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "mix",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Jetour", "MG", "used BMW"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 50, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Rukn Al Mustaqbal Cars", nameAr: "معرض ركن المستقبل للسيارات", lat: 24.823414, lng: 46.820395,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "mix",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Lexus", "Toyota", "used Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Asdaa Cars", nameAr: "شركة اصداء للسيارات", lat: 24.823396, lng: 46.820389,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Hyundai", "Kia"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Rayat Al Ezz Cars", nameAr: "معرض راية العز", lat: 24.823552, lng: 46.82073,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Haval", "Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 4, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Terhal Cars", nameAr: "ترحال للسيارات", lat: 24.823837, lng: 46.821391,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Kia", "BAIC"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 5, inventorySellableUnits: 65, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Rimal Cars", nameAr: "شركة الرمال للسيارات", lat: 24.82394, lng: 46.821563,
    showroomSizeSqm: 1000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 80, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Fakhamat Najd Cars", nameAr: "معرض فخامة نجد للسيارات", lat: 24.825299, lng: 46.821343,
    showroomSizeSqm: 1350, sizeBasis: "estimated", vehicleType: "mix",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Ford", "used cars"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 80000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Nayef Cars", nameAr: "شركة معرض النايف للسيارات", lat: 24.825117, lng: 46.822102,
    showroomSizeSqm: 1350, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Hyundai", "Changan"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Auto One", nameAr: "اوتو ون", lat: 24.825033, lng: 46.821623,
    showroomSizeSqm: 2400, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Kia", "Jetour", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 9, inventorySellableUnits: 90, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Wisam Al Majd", nameAr: "شركة وسام المجد", lat: 24.825642, lng: 46.822089,
    showroomSizeSqm: 1200, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Kia", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 8, inventorySellableUnits: 110, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Qimah", nameAr: "القيمة", lat: 24.827677, lng: 46.821175,
    showroomSizeSqm: 2000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Chevrolet SUVs", "Nissan SUVs", "Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 8, inventorySellableUnits: 110, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Emlaq", nameAr: "العملاق", lat: 24.827372, lng: 46.822202,
    showroomSizeSqm: 2300, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Lexus", "Toyota", "Mitsubishi"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 6, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 140000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Nukhbat Bahwan", nameAr: "نخبة بهوان", lat: 24.829738, lng: 46.818514,
    showroomSizeSqm: 2400, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Lexus", "Land Cruiser", "high-end Nissan"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 60, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 345000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Bilad Shahran Cars", nameAr: "معرض بلاد شهران للسيارات", lat: 24.829736, lng: 46.81906,
    showroomSizeSqm: 1200, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Land Cruiser", "Nissan Patrol", "Toyota", "Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 70, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 229999.99999999997, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Qimmat Al Fursan Cars", nameAr: "معرض قمة الفرسان للسيارات", lat: 24.830049, lng: 46.819291,
    showroomSizeSqm: 1800, sizeBasis: "estimated", vehicleType: "used_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Chevrolet SUVs", "BMW", "Geely", "Hyundai"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 80, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 75000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Ramz Al Emarat", nameAr: "رمز الإمارات", lat: 24.827731, lng: 46.82004,
    showroomSizeSqm: 5000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "unclear", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Hyundai", "Nissan"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 10, inventorySellableUnits: 190, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 130000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Adwaa Khamis Mushait Cars", nameAr: "شركة أضواء خميس مشيط للسيارات", lat: 24.828776, lng: 46.820224,
    showroomSizeSqm: 5000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "unclear", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Toyota", "Hyundai", "Isuzu"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 11, inventorySellableUnits: 125, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 130000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Qimmat Al Wafi Cars", nameAr: "معرض قمة الوافي للسيارات", lat: 24.828105, lng: 46.833433,
    showroomSizeSqm: 2400, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "yes", authorisedBrand: "Isuzu", buyerMix: null,
    mainBrands: ["Isuzu"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 65, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 110000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Falah Cars", nameAr: "شركة الفلاح للسيارات", lat: 24.819202, lng: 46.826335,
    showroomSizeSqm: 5000, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "yes", authorisedBrand: "Nissan", buyerMix: null,
    mainBrands: ["Toyota", "Hyundai", "Nissan"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 13, inventorySellableUnits: 180, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Adel Cars", nameAr: "شركة عادل للسيارات", lat: 24.820526, lng: 46.824775,
    showroomSizeSqm: 2400, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Hyundai", "Changan", "JAC", "Land Rover"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 7, inventorySellableUnits: 80, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Burj Al Diwaniyah Cars", nameAr: "شركة برج الديوانية للسيارات", lat: 24.823445, lng: 46.824264,
    showroomSizeSqm: 2400, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "yes", authorisedBrand: "Toyota", buyerMix: null,
    mainBrands: ["Toyota", "Nissan", "Hyundai", "Kia"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 3, inventorySellableUnits: 120, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 150000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Wosta Used Cars", nameAr: "وسطى", lat: 24.822832, lng: 46.818988,
    showroomSizeSqm: 3100, sizeBasis: "estimated", vehicleType: "used_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Used cars"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 2, inventorySellableUnits: 130, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 70000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
  {
nameEn: "Al Qimah Second Branch", nameAr: "2القيمة", lat: 24.828503, lng: 46.820731,
    showroomSizeSqm: 2200, sizeBasis: "estimated", vehicleType: "new_only",
    authorised: "no", authorisedBrand: "", buyerMix: null,
    mainBrands: ["Nissan", "Chevrolet", "Hyundai", "MG"], pocName: "", pocRole: "", pocMobile: "",
    numSalesmen: 7, inventorySellableUnits: 95, inventoryCountBasis: "estimated",
    avgSellingPriceSar: 120000, avgMonthlySold: null, avgMonthlyFinanced: null,
    banksPartnered: [], bankOnSite: null, financingWorkaround: "",
    leadMixOnlinePct: null, volumeFiguresBasis: null, visitStatus: "partial",
    notes: "",
  },
];

// Combined starting roster: the mapping-data list (enriched wherever a field
// survey confirmed the same physical dealership) plus the additional distinct
// dealerships the field survey found nearby. This market has many showrooms
// per block, so close GPS coordinates do not by themselves imply duplicates —
// only matching names were merged.
export function buildSeedDealerships(): Dealership[] {
  return [...buildMappingSeedDealerships(), ...buildMasterSurveyDealerships()];
}
