// Builds src/content/routesStatic.ts: real driving routes for the route console's flyover.
//   node --experimental-strip-types scripts/build-routes.mjs [--all] [--base https://your-osrm-server]
// Default scope: Riyadh (districts + hub) and Sabya (areas + logistics centre). --all adds every other city.
// Asks the public OSRM demo server politely (one request every 1.2 s); use --base for your own server.
import { writeFileSync } from "node:fs";
import { AREAS, CITIES } from "../src/content/routeConsole.ts";
import { CITY_LL, SITE_LL, placeLL } from "../src/content/routeGeo.ts";
import { routeKey } from "../src/lib/routing.ts";

const args = process.argv.slice(2);
const all = args.includes("--all");
const base = (args[args.indexOf("--base") + 1] && args.includes("--base") ? args[args.indexOf("--base") + 1] : "https://router.project-osrm.org").replace(/\/$/, "");

const nodes = (city) => {
  const areas = (city === "riyadh" ? AREAS.riyadh : AREAS.other).map((a) => placeLL({ city, fx: a.fx, fy: a.fy, pin: "door" }));
  const extra = city === "riyadh" ? [SITE_LL.riyadh] : city === "sabya" ? [SITE_LL.sabya, CITY_LL.sabya] : [CITY_LL[city]];
  const seen = new Set();
  return [...areas, ...extra].filter((p) => !seen.has(p.join()) && seen.add(p.join()));
};
const cities = all ? CITIES : ["riyadh", "sabya"];
const pairs = [];
for (const c of cities) for (const a of nodes(c)) for (const b of nodes(c)) if (a !== b) pairs.push([a, b]);

console.log(`${pairs.length} routes from ${base}`);
const out = {};
let failed = 0;
for (const [i, [a, b]] of pairs.entries()) {
  try {
    const res = await fetch(`${base}/route/v1/driving/${a[0]},${a[1]};${b[0]},${b[1]}?overview=full&geometries=polyline&steps=false`);
    const j = await res.json();
    const g = j?.routes?.[0]?.geometry;
    if (!g) throw new Error(j?.code || res.status);
    out[routeKey(a, b)] = g;
  } catch (e) {
    failed++;
    console.warn(`  skipped ${routeKey(a, b)}: ${e.message}`);
  }
  if ((i + 1) % 20 === 0) console.log(`  ${i + 1}/${pairs.length}`);
  await new Promise((r) => setTimeout(r, 1200));
}
const body = Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
writeFileSync(new URL("../src/content/routesStatic.ts", import.meta.url), `/**
 * Pre-computed driving routes for the route console's flyover (generated by scripts/build-routes.mjs).
 * Keys come from routeKey() in src/lib/routing.ts; values are encoded polylines (precision 5).
 */
export const ROUTES_STATIC: Record<string, string> = {
${body}
};
`);
console.log(`wrote ${Object.keys(out).length} routes${failed ? `, ${failed} skipped` : ""}`);
