// Generates src/lib/ksa-geo.ts from Natural Earth (world-atlas 50m).
// Output is normalised to a 0..1000 x-space with correct aspect ratio.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";

const topo = JSON.parse(readFileSync("node_modules/world-atlas/countries-50m.json", "utf8"));
const countries = feature(topo, topo.objects.countries);
const ksa = countries.features.find((f) => f.id === "682");
if (!ksa) throw new Error("Saudi Arabia not found");

const polys = ksa.geometry.type === "Polygon" ? [ksa.geometry.coordinates] : ksa.geometry.coordinates;
// keep the mainland (largest ring)
const ring = polys.map((p) => p[0]).sort((a, b) => b.length - a.length)[0];

const LAT0 = 24; // equirectangular with cos(lat0) correction
const k = Math.cos((LAT0 * Math.PI) / 180);
const proj = ([lon, lat]) => [lon * k, -lat];
const pts = ring.map(proj);
const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys);
const W = 1000, scale = W / (maxX - minX), H = (maxY - minY) * scale;
const norm = ([x, y]) => [+((x - minX) * scale).toFixed(1), +((y - minY) * scale).toFixed(1)];

// simplify: drop points closer than 4 units
const outline = [];
for (const p of pts.map(norm)) {
  const last = outline[outline.length - 1];
  if (!last || Math.hypot(p[0] - last[0], p[1] - last[1]) > 4) outline.push(p);
}

function inside([x, y], poly) {
  let c = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i], [xj, yj] = poly[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) c = !c;
  }
  return c;
}

// hex grid; search spacing that yields ~1,000 dots (one per courier)
function grid(s) {
  const out = [];
  for (let r = 0, y = s / 2; y < H; y += s * 0.866, r++)
    for (let x = (r % 2 ? s : s / 2); x < W; x += s)
      if (inside([x, y], outline)) out.push([+x.toFixed(1), +y.toFixed(1)]);
  return out;
}
let s = 30, dots = grid(s);
while (dots.length < 1000) { s -= 0.05; dots = grid(s); }

const riyadh = norm(proj([46.7219, 24.6877]));
const src = `// AUTO-GENERATED by scripts/build-ksa-geo.mjs from Natural Earth (public domain).
// Coordinates are normalised: x in [0, ${W}], y in [0, ${H.toFixed(0)}].
export const KSA_WIDTH = ${W};
export const KSA_HEIGHT = ${H.toFixed(1)};
/** Headquarters (Riyadh) — the only location stated in the source material. */
export const RIYADH: [number, number] = ${JSON.stringify(riyadh)};
export const KSA_OUTLINE: [number, number][] = ${JSON.stringify(outline)};
/** Hex-grid sample of the Kingdom: ${dots.length} points, used as one-dot-per-courier targets. */
export const KSA_DOTS: [number, number][] = ${JSON.stringify(dots)};
`;
writeFileSync("src/lib/ksa-geo.ts", src);
console.log({ outline: outline.length, dots: dots.length, spacing: s.toFixed(2), H: H.toFixed(0), riyadh });
